"""removed duration

Revision ID: 74c694a5f0bd
Revises: a329bf65c450
Create Date: 2026-04-14 16:16:59.845607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c694a5f0bd'
down_revision = 'a329bf65c450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.drop_column('duration')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
